namespace:
  name: sandbox

image:
  repository:
     matheus06/techtrends
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    memory: 64Mi
    cpu: 250m
  limits:
    memory: 128Mi
    cpu: 500m

containerPort: 3111

livenessProbe:
  path: /healthz

readinessProbe:
  path: /healthz